In [21]:
from qutip import *
import numpy as np
import scipy as sp

pi = sp.pi
hbar = 1.0
wAtom = 1.0 *2.0*pi  #atomic transition frequency
wRFx = 1.0 *2.0*pi   #rf trap drive frequency in x
wRFy = 1.0 *2.0*pi   #rf trap drive frequency in y
wz = 1.0 *2.0*pi     #effective potential in axial direction
m = 1.0              #ion mass
Omega0 = 

N = 2
a = destroy(N)

#operator = tensor(internal states, x motion, y motion, z motion)
ax = tensor(qeye(2), a, qeye(N), qeye(N))
ay = tensor(qeye(2), qeye(N), a, qeye(N))
az = tensor(qeye(2), qeye(N), qeye(N), a)
sz = tensor(sigmaz(), qeye(N), qeye(N), qeye(N)) #sigma z

sPlus = 0.5*(sigmax()- 1.0j*sigmay())
splus = tensor(sPlus, qeye(N), qeye(N), qeye(N))
sMinus = 0.5*(sigmax() + 1.0j*sigmay())
sminus = tensor(sMinus, qeye(N), qeye(N), qeye(N))

Hatom = -hbar*wAtom/2.0*sz
HmotionX = hbar*wRFx*(ax*ax.dag() + 0.5)
HmotionY = hbar*wRFy*(ay*ay.dag() + 0.5)
HmotionZ = hbar*wz*(az*az.dag() + 0.5)

Hint = ???

In [2]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [3]:
sigmax()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [14]:
psi0 = tensor(basis(2,1), basis(N,0), basis(N,0), basis(N,0))
Hatom*psi0

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-3.14159265]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]

In [15]:
psi0

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [16]:
basis(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [4]:
sigmaz()*basis(2,0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [5]:
sigmay()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [6]:
sigmay()*basis(2,0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.+0.j]
 [0.+1.j]]

In [7]:
sigmay()*basis(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.-1.j]
 [0.+0.j]]

In [17]:

sPlus*basis(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]

In [15]:
basis(2,0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [20]:
sMinus = 0.5*(sigmax() + 1.0j*sigmay())
sMinus*basis(2,0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [0.]]